import { type Metadata } from "next";
import Link from "next/link";
import SiteFooter from "~/fsd/widgets/site-footer/ui";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "AI Podcast Clipper Privacy Policy",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <header className="mb-12">
        <Link
          href="/"
          className="text-muted-foreground hover:text-foreground text-sm underline-offset-4 hover:underline"
        >
          &larr; AI Podcast Clipper
        </Link>
      </header>

      <div className="space-y-10">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight">
            Privacy Policy
          </h1>
          <p className="text-muted-foreground mt-2 text-sm">
            Effective date: June 16, 2026
          </p>
        </div>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold tracking-tight">
            1. Data Controller
          </h2>
          <ul className="text-muted-foreground list-disc space-y-1 pl-6">
            <li>Controller: HamSangEok</li>
            <li>
              Contact:{" "}
              <a
                href="mailto:hamsoo159@gmail.com"
                className="underline underline-offset-4"
              >
                hamsoo159@gmail.com
              </a>
            </li>
          </ul>
        </section>

        <section className="space-y-6">
          <h2 className="text-xl font-semibold tracking-tight">
            2. Personal Data We Collect
          </h2>

          <div className="space-y-3">
            <h3 className="text-base font-medium">Account Information</h3>
            <div className="overflow-x-auto">
              <table className="text-muted-foreground w-full text-sm">
                <thead>
                  <tr className="border-border border-b">
                    <th className="text-foreground py-2 pr-4 text-left font-medium">
                      Data
                    </th>
                    <th className="text-foreground py-2 text-left font-medium">
                      Source
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">Email address</td>
                    <td className="py-2">Google OAuth</td>
                  </tr>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">Name</td>
                    <td className="py-2">Google OAuth</td>
                  </tr>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">Profile image URL</td>
                    <td className="py-2">Google OAuth</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div className="space-y-3">
            <h3 className="text-base font-medium">Service Usage Data</h3>
            <div className="overflow-x-auto">
              <table className="text-muted-foreground w-full text-sm">
                <thead>
                  <tr className="border-border border-b">
                    <th className="text-foreground py-2 pr-4 text-left font-medium">
                      Data
                    </th>
                    <th className="text-foreground py-2 text-left font-medium">
                      Description
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">Uploaded video files</td>
                    <td className="py-2">
                      Original videos uploaded by users and stored in AWS S3
                    </td>
                  </tr>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">Generated clip files</td>
                    <td className="py-2">
                      Short-form clips generated by AI and stored in AWS S3
                    </td>
                  </tr>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">Transcript text</td>
                    <td className="py-2">
                      Transcripts generated by WhisperX and Gemini
                    </td>
                  </tr>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">YouTube metadata</td>
                    <td className="py-2">
                      Titles, descriptions, and hashtags generated by Gemini
                    </td>
                  </tr>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">Credit balance</td>
                    <td className="py-2">Used to manage service usage</td>
                  </tr>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">Product analytics events</td>
                    <td className="py-2">
                      Pseudonymous page and product milestone events used to
                      understand onboarding, upload, processing, and billing
                      drop-off.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div className="space-y-3">
            <h3 className="text-base font-medium">Payment Data</h3>
            <div className="overflow-x-auto">
              <table className="text-muted-foreground w-full text-sm">
                <thead>
                  <tr className="border-border border-b">
                    <th className="text-foreground py-2 pr-4 text-left font-medium">
                      Data
                    </th>
                    <th className="text-foreground py-2 text-left font-medium">
                      Description
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">Polar customer ID</td>
                    <td className="py-2">
                      Identifier linked to payment processing. We do not store
                      credit card details.
                    </td>
                  </tr>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">Subscription and order records</td>
                    <td className="py-2">
                      Plan, amount, status, and subscription period
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div className="space-y-3">
            <h3 className="text-base font-medium">Cookies</h3>
            <p className="text-muted-foreground text-sm">
              We only use cookies required for authentication. We do not use
              analytics or advertising cookies. We use local browser storage to
              keep a pseudonymous analytics identifier and session identifier
              for first-party product analytics.
            </p>
            <div className="overflow-x-auto">
              <table className="text-muted-foreground w-full text-sm">
                <thead>
                  <tr className="border-border border-b">
                    <th className="text-foreground py-2 pr-4 text-left font-medium">
                      Cookie
                    </th>
                    <th className="text-foreground py-2 pr-4 text-left font-medium">
                      Purpose
                    </th>
                    <th className="text-foreground py-2 text-left font-medium">
                      Retention
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">authjs.session-token</td>
                    <td className="py-2 pr-4">JWT session authentication</td>
                    <td className="py-2">30 days</td>
                  </tr>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">authjs.csrf-token</td>
                    <td className="py-2 pr-4">CSRF protection</td>
                    <td className="py-2">Session</td>
                  </tr>
                  <tr className="border-border border-b">
                    <td className="py-2 pr-4">authjs.callback-url</td>
                    <td className="py-2 pr-4">OAuth redirect handling</td>
                    <td className="py-2">Session</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold tracking-tight">
            3. Third-Party Processing
          </h2>
          <div className="overflow-x-auto">
            <table className="text-muted-foreground w-full text-sm">
              <thead>
                <tr className="border-border border-b">
                  <th className="text-foreground py-2 pr-4 text-left font-medium">
                    Service
                  </th>
                  <th className="text-foreground py-2 pr-4 text-left font-medium">
                    Data Transferred
                  </th>
                  <th className="text-foreground py-2 pr-4 text-left font-medium">
                    Purpose
                  </th>
                  <th className="text-foreground py-2 text-left font-medium">
                    Server Location
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Google OAuth</td>
                  <td className="py-2 pr-4">Email, name, profile image</td>
                  <td className="py-2 pr-4">User authentication</td>
                  <td className="py-2">United States</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Google Gemini API</td>
                  <td className="py-2 pr-4">Transcript text</td>
                  <td className="py-2 pr-4">
                    AI highlight detection and metadata generation
                  </td>
                  <td className="py-2">United States</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">AWS S3</td>
                  <td className="py-2 pr-4">Video files and clip files</td>
                  <td className="py-2 pr-4">File storage</td>
                  <td className="py-2">Asia Pacific (Sydney)</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Neon</td>
                  <td className="py-2 pr-4">Application database records</td>
                  <td className="py-2 pr-4">Database hosting</td>
                  <td className="py-2">United States</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Polar</td>
                  <td className="py-2 pr-4">Email and payment records</td>
                  <td className="py-2 pr-4">Payment processing</td>
                  <td className="py-2">United States</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Modal.com</td>
                  <td className="py-2 pr-4">Video files</td>
                  <td className="py-2 pr-4">GPU video processing</td>
                  <td className="py-2">United States</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Inngest</td>
                  <td className="py-2 pr-4">Background job event data</td>
                  <td className="py-2 pr-4">Background job processing</td>
                  <td className="py-2">United States</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Vercel</td>
                  <td className="py-2 pr-4">Request logs</td>
                  <td className="py-2 pr-4">Application hosting</td>
                  <td className="py-2">Seoul</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold tracking-tight">
            4. Data Retention
          </h2>
          <div className="overflow-x-auto">
            <table className="text-muted-foreground w-full text-sm">
              <thead>
                <tr className="border-border border-b">
                  <th className="text-foreground py-2 pr-4 text-left font-medium">
                    Data Type
                  </th>
                  <th className="text-foreground py-2 text-left font-medium">
                    Retention Period
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Account information</td>
                  <td className="py-2">Until the account is deleted</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Video and clip files</td>
                  <td className="py-2">Until deleted by the user</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Transcripts and metadata</td>
                  <td className="py-2">Until the related clip is deleted</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Payment records</td>
                  <td className="py-2">5 years, where required by law</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Temporary scene detection data</td>
                  <td className="py-2">Deleted immediately after processing</td>
                </tr>
                <tr className="border-border border-b">
                  <td className="py-2 pr-4">Product analytics events</td>
                  <td className="py-2">
                    90 days maximum for raw analytics events. User-linked rows
                    are deleted earlier when the linked account is deleted.
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold tracking-tight">
            5. Data Protection
          </h2>
          <ul className="text-muted-foreground list-disc space-y-1 pl-6">
            <li>All communications are encrypted over HTTPS.</li>
            <li>
              Session tokens are managed with httpOnly and Secure cookies.
            </li>
            <li>
              Credit card information is not stored in our database. Polar
              manages payment card data and PCI DSS compliance.
            </li>
            <li>
              Scene detection data is processed temporarily for video analysis
              and is not stored in the database.
            </li>
            <li>
              Product analytics events do not include uploaded file names, video
              URLs, S3 keys, payment card details, or OAuth tokens.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold tracking-tight">
            6. User Rights
          </h2>
          <ul className="text-muted-foreground list-disc space-y-1 pl-6">
            <li>
              You may request access to, correction of, or deletion of your
              personal data.
            </li>
            <li>
              When account deletion is requested, all related data, including
              database records and stored files, will be deleted.
            </li>
            <li>
              To submit a request, contact us at{" "}
              <a
                href="mailto:hamsoo159@gmail.com"
                className="underline underline-offset-4"
              >
                hamsoo159@gmail.com
              </a>
              .
            </li>
          </ul>
        </section>
      </div>

      <SiteFooter />
    </div>
  );
}
